[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
# Content-Security-Policy= "frame-ancestors 'self' https://verify.walletconnect.com;"
