name: deploy flow

on:
  push:
    branches:
      - 'dev'
      - 'staging'
      - 'main'
      
env:
   NODE_OPTIONS: --max-old-space-size=32768

jobs:    
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false
            
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: pnpm
          
      - name: Print GitHub variables
        run: |
          echo "Branch or tag ref is ${{ github.ref }}"
          echo "VITE_APP_TEST is ${{ vars.VITE_APP_TEST }}"
          echo "VITE_APP_BASE is ${{ vars.VITE_APP_BASE }}"

      

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      
      - name: Install pnpm
        run: |
          pnpm install --frozen-lockfile

      - name: build
        run: |
          pnpm build
        env:
          VITE_APP_TEST: ${{ vars.VITE_APP_TEST }}
          VITE_APP_BASE: ${{ vars.VITE_APP_BASE }}


      - name: Deploy to netlify
        uses: South-Paw/action-netlify-cli@v2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
